export const pagesList = {
  '/news': 'Новости',
  '/news/shelternews': 'Новости приюта',
  '/news/worldnews': 'Новости мира',
  '/news/actions': 'Акции приюта',
  '/news/newsaboutus': 'СМИ о нас',
  '/lodgers': 'Животные',
  '/lodgers/newbies': 'Новички',
  '/lodgers/finders': 'Ищут дом',
  '/lodgers/hards': 'Сложный случай',
  '/lodgers/founds': 'Нашли дом',
  '/help': 'Помощь',
  '/help/howhelp': 'Как помочь',
  '/help/donate': 'Помощь онлайн',
  '/info': 'Информация',
  '/info/about': 'О нас',
  '/info/communication': 'Контакты',
  '/info/docs': 'Документы',
  '/info/toowners': 'Правила',
  '/user': 'Профиль',
  '/user/login': 'Вход',
  '/user/register': 'Регистрация'
}
